---
- name: Testing Juniper and Ansible
  hosts: pynet-sf-srx
  tasks:
    - name: Verifying NETCONF
      wait_for: host={{ ansible_ssh_host }} port=830

    - name: Add a static route
      junos_install_config:
        host={{ ansible_ssh_host }}
        file=hostname.xml
        overwrite=false
        user={{ juniper_user }}
        passwd={{ juniper_passwd }}