---

- name: Setting Arista Interfaces
  hosts: arista

  tasks:
    - name: Setting description Ethernet3 interface
      eos_interface: name=Ethernet3 description="*** IN USE ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Setting Ethernet3 vlan and switchport mode 
      eos_switchport: name=Ethernet3 mode=access access_vlan=101
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
