---

- name: Create Arista VLANs
  hosts: arista

  tasks:
    - name: create DATACENTER VLAN
      eos_vlan: name=DATACENTER vlanid=100
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: create VOIP VLAN
      eos_vlan: name=VOIP vlanid=101
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: create GUEST VLAN
      eos_vlan: name=GUEST vlanid=102
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https























