---

- name: Cisco File Transfer
  hosts: cisco-rtr1
  gather_facts: False

  tasks:
  - name: File Transfering
    cisco_file_transfer:
      source_file="/home/jbenito/ANSIBLE/cisco_transfer_test.txt"
      dest_file=cisco_transfer_test.txt
      overwrite=false
      enable_scp=true
      host={{ host }}
      port={{ port }}
      username={{ username }}
      password={{ password }}
